listener 1883
protocol mqtt
allow_anonymous false
password_file /tmp/mosquitto-passwords
acl_file /tmp/mosquitto-acl
message_size_limit 65536

persistence true
persistence_location /mosquitto/data/
log_dest stdout
